'use client';
import { useState, useRef, useCallback } from 'react';
import ReactCrop, { Crop, PixelCrop } from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';
interface ImageCropProps { imageSrc: string; onCropComplete: (blob: Blob) => void; onCancel: () => void; aspectRatio?: number; }
function getCroppedCanvas(img: HTMLImageElement, crop: PixelCrop) { const c = document.createElement('canvas'); const ctx = c.getContext('2d'); if (!ctx) return null; const sx = img.naturalWidth/img.width, sy = img.naturalHeight/img.height; c.width = Math.floor(crop.width*sx); c.height = Math.floor(crop.height*sy); ctx.imageSmoothingQuality = 'high'; ctx.drawImage(img, crop.x*sx, crop.y*sy, crop.width*sx, crop.height*sy, 0, 0, c.width, c.height); return c; }
export default function ImageCrop({ imageSrc, onCropComplete, onCancel, aspectRatio }: ImageCropProps) {
  const imgRef = useRef<HTMLImageElement|null>(null);
  const [crop, setCrop] = useState<Crop>({unit:'%',width:80,height:80,x:10,y:10});
  const [done, setDone] = useState<PixelCrop|null>(null);
  const [saving, setSaving] = useState(false);
  const [aspect, setAspect] = useState(aspectRatio);
  const save = useCallback(async () => { if (!done||!imgRef.current) return; setSaving(true); const c = getCroppedCanvas(imgRef.current, done); if (!c) { setSaving(false); return; } c.toBlob(b => { if (b) onCropComplete(b); setSaving(false); }, 'image/jpeg', 0.9); }, [done, onCropComplete]);
  return (<div style={{position:'fixed',inset:0,zIndex:10000,background:'rgba(0,0,0,0.7)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:20}}><div style={{background:'#fff',borderRadius:16,padding:20,maxWidth:600,width:'100%',maxHeight:'85vh',overflow:'auto'}}><h3 style={{margin:'0 0 16px',fontSize:18,fontWeight:700}}>✂️ 사진 크롭</h3><div style={{display:'flex',justifyContent:'center',marginBottom:16}}><ReactCrop crop={crop} onChange={c=>setCrop(c)} onComplete={c=>setDone(c)} aspect={aspect} style={{maxHeight:'55vh'}}><img ref={imgRef} src={imageSrc} alt='' style={{maxWidth:'100%',maxHeight:'55vh',objectFit:'contain'}} crossOrigin='anonymous'/></ReactCrop></div><div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap',justifyContent:'center'}}>{[{l:'자유',r:undefined},{l:'1:1',r:1},{l:'4:3',r:4/3},{l:'16:9',r:16/9}].map(p=>(<button key={p.l} onClick={()=>{setAspect(p.r);setCrop({unit:'%',width:80,height:80,x:10,y:10})}} style={{padding:'6px 14px',border:aspect===p.r?'2px solid #FF3B1E':'1px solid #ddd',borderRadius:8,background:aspect===p.r?'#FFF5F4':'#f9f9f9',fontSize:13,cursor:'pointer',color:aspect===p.r?'#FF3B1E':'#555',fontWeight:aspect===p.r?700:400}}>{p.l}</button>))}</div><div style={{display:'flex',gap:10,justifyContent:'flex-end'}}><button onClick={onCancel} style={{padding:'10px 24px',border:'1px solid #ddd',borderRadius:10,background:'#fff',fontSize:14,fontWeight:600,cursor:'pointer',color:'#666'}}>취소</button><button onClick={save} disabled={saving||!done} style={{padding:'10px 24px',border:'none',borderRadius:10,background:saving?'#ccc':'#FF3B1E',color:'#fff',fontSize:14,fontWeight:700,cursor:saving?'default':'pointer'}}>{saving?'처리 중...':'✓ 적용'}</button></div></div></div>);
}